app_env: "${oc.env:APP_ENV, ''}"
app_url: "${oc.env:APP_URL, 'http://localhost:8000'}"

uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: False
  log_level: "debug"
  workers: 1
  limit_concurrency: 7
  limit_max_requests: 50

redis:
  host: "localhost"
  port: 6379
  db: 0
  decode_responses: True

email: "amirbahador.develop@gmail.com"